CREATE TABLE [dbo].[Filer] (
    [Id]                                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [FirstName]                           NVARCHAR (200) NOT NULL,
    [LastName]                            NVARCHAR (200) NOT NULL,
    [MiddleName]                          NVARCHAR (200) NULL,
    [EmailAddress]                        NVARCHAR (200) NULL,
    [EFMUserId]                           NVARCHAR (200) NULL,
    [Password]                            NVARCHAR (200) NULL,
    [SecurityQuestion]                    NVARCHAR (200) NULL,
    [SecurityAnswer]                      NVARCHAR (200) NULL,
    [Roles]                               NVARCHAR (255) NOT NULL,
    [IsApproved]                          BIT            NULL,
    [IsActive]                            BIT            NULL,
    [IsLockedOut]                         BIT            NULL,
    [ActiveIndicator]                     BIT            NULL,
    [LastUpdateFromEFM]                   DATETIME       NULL,
    [LastLogin]                           DATETIME       NULL,
    [LastLoginToEFM]                      DATETIME       NULL,
    [UserSince]                           DATETIME       NULL,
    [FTUserSince]                         DATETIME       NULL,
    [FilingAcceptedNotification]          BIT            NULL,
    [FilingRejectedNotification]          BIT            NULL,
    [FilingSubmitedNotification]          BIT            NULL,
    [FilingFailedNotification]            BIT            NULL,
    [ServiceStatusNotification]           BIT            NULL,
    [eFileTexasNotiPref]                  NVARCHAR (255) NULL,
    [FirmSubmissionsWaitingOnClerkReview] BIT            NULL,
    [FirmSubmissionsReturnedByTheClerk]   BIT            NULL,
    [RestrictFiling]                      BIT            NULL,
    [RestrictFilingComment]               NVARCHAR (255) NULL,
    [ShowWelcomePageAtLogin]              BIT            NULL,
    [Firm_id]                             BIGINT         NOT NULL,
    [Attoney_id]                          BIGINT         NULL,
    [HeardAboutFiletime]                  NVARCHAR (255) NULL,
    [ReferrerEmailAddress]                NVARCHAR (255) NULL,
    [Other]                               NVARCHAR (255) NULL,
    [ActivationLink]                      NVARCHAR (255) NULL,
    [PasswordResetLink]                   NVARCHAR (255) NULL,
    [LastFilingUpdateFromEFM]             DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([EmailAddress] ASC)
);

